branch-defaults:
  master:
    environment: profile
    group_suffix: null
global:
  application_name: django-tutorial-2
  branch: null
  default_ec2_keyname: TokyoSparkKeyPair
  default_platform: python2.7
  default_region: ap-northeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
